<?php
/**
 * @link http://www.diecoding.com/
 * @author Die Coding (Sugeng Sulistiyawan) <diecoding@gmail.com>
 * @copyright Copyright (c) 2018
 */

/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */
 return [
   'color' => null,
   'interactive' => true,
   'help' => null,
   'sourcePath' => '@diecoding',
   'messagePath' => '@diecoding/i18n',
   'languages' => [
     'en',
     'id',
   ],
   'translator' => 'Yii::t',
   'sort' => true,
   'overwrite' => false,
   'removeUnused' => true,
   'markUnused' => true,
   'except' => [
     '.svn',
     '.git',
     '.gitignore',
     '.gitkeep',
     '.hgignore',
     '.hgkeep',
     '/messages',
     '/i18n',
     '/BaseYii.php',
   ],
   'only' => [
     '*.php',
   ],
   'format' => 'php',
   'db' => 'db',
   'sourceMessageTable' => '{{%source_message}}',
   'messageTable' => '{{%message}}',
   'catalog' => 'messages',
   'ignoreCategories' => [
     'app',
     'yii',
   ],
   'fileMap' => [
     'diecoding' => 'diecoding.php',
   ],
   'phpFileHeader' => '/**
 * @link http://www.diecoding.com/
 * @author Die Coding (Sugeng Sulistiyawan) <diecoding@gmail.com>
 * @copyright Copyright (c) '. date('Y') .'
 */

',
   'phpDocBlock' => null,
 ];
